import "dotenv/config";
import { PrismaClient } from "../src/generated/client";
import { PrismaBetterSqlite3 } from "@prisma/adapter-better-sqlite3";
import path from "path";

let dbPath = "dev.db";
const databaseUrl = process.env.DATABASE_URL;
if (databaseUrl && databaseUrl.startsWith("file:")) {
  dbPath = databaseUrl.replace("file:", "");
}
const absDbPath = path.resolve(process.cwd(), dbPath);
const adapter = new PrismaBetterSqlite3({ url: `file:${absDbPath}` });
const prisma = new PrismaClient({ adapter });

async function main() {
  console.log("Seeding started...");

  // Clean existing data
  await prisma.taskSubmission.deleteMany({});
  await prisma.task.deleteMany({});
  await prisma.student.deleteMany({});
  await prisma.blog.deleteMany({});
  await prisma.contactQuery.deleteMany({});
  await prisma.clientInvoice.deleteMany({});
  await prisma.clientProject.deleteMany({});
  await prisma.client.deleteMany({});

  console.log("Cleaned database.");

  // 1. Seed Blogs
  await prisma.blog.createMany({
    data: [
      {
        title: "The Future of AI-First Software Development",
        slug: "future-of-ai-first-development",
        category: "Artificial Intelligence",
        content: `As artificial intelligence models like Claude, GPT-4, and Gemini evolve, the landscape of software engineering is undergoing a paradigm shift. We are transitioning from traditional manual coding to AI-augmented coding, where engineers act as directors, architects, and quality inspectors of code generated by AI models.

At ProDevOpz, we embrace this future. We build software platforms where AI agents manage automated deployments, perform linting checks, write tests, and optimize database schemas in real-time. The developer of tomorrow is not a syntax writer, but an architectural systems designer.`,
        readingTime: "5 min read",
        author: "Ammar, CTO ProDevOpz",
      },
      {
        title: "Mastering Cloud Infrastructure with Devops Automation",
        slug: "mastering-cloud-infrastructure-devops",
        category: "Cloud & DevOps",
        content: `DevOps is not just a role; it is a philosophy. By integrating Continuous Integration and Continuous Deployment (CI/CD) pipelines, container orchestrations using Kubernetes, and Infrastructure as Code (IaC) with Terraform, modern enterprises can ship code 100x faster.

This guide outlines our internal pipeline structure at ProDevOpz, showcasing how we manage containerized Next.js applications, handle automated scale-ups during peak traffic, and secure database migrations without downtime.`,
        readingTime: "8 min read",
        author: "DevOps Team",
      },
      {
        title: "Why Startups Should Choose Next.js 15 and Tailwind v4",
        slug: "nextjs15-tailwind-v4-for-startups",
        category: "Web Development",
        content: `Building a startup product requires rapid iteration, stunning visual aesthetics, and top-tier SEO right out of the box. Next.js 15 combined with the brand-new Tailwind CSS v4 delivers exactly that.

With Server Actions, partial pre-rendering (PPR), and Tailwind's blazing-fast PostCSS compile times, startup founders can deliver Stripe-like fluid UI animations and achieve 100% Lighthouse scores with minimal friction. Learn how to scaffold your next SaaS MVP using this modern web stack.`,
        readingTime: "6 min read",
        author: "Design Team",
      },
    ],
  });

  console.log("Seeded blogs.");

  // 2. Seed Tasks for Domains
  const domains = [
    "Web Development",
    "Frontend",
    "Backend",
    "Full Stack",
    "AI",
    "Machine Learning",
    "Cloud",
    "DevOps",
    "UI UX",
    "Cyber Security",
    "Android",
  ];

  for (const domain of domains) {
    const isWeb = ["Web Development", "Frontend", "Backend", "Full Stack"].includes(domain);
    const isAI = ["AI", "Machine Learning"].includes(domain);
    const isAndroid = domain === "Android";

    let taskData = [];

    if (isWeb) {
      taskData = [
        {
          title: "Development Environment Setup & Git Integration",
          description: "Download and install VS Code, Node.js (LTS), and Git. Initialize a GitHub repository named 'prodevopz-web-sprint', add a README.md file summarizing your goals, and commit it using Git CLI. Submit the repository URL.",
          dayNumber: 1,
          resourceLinks: JSON.stringify([
            { name: "Node.js Guide", url: "https://nodejs.org/" },
            { name: "Git & GitHub Crash Course", url: "https://docs.github.com/en/get-started" },
          ]),
        },
        {
          title: "Responsive Portfolio Section HTML5/CSS3 Layout",
          description: "Build a responsive bio portfolio section. Use semantic tags (nav, header, section, footer) and styled CSS Flexbox/Grid elements to construct a grid containing your bio, tech stack icons, and contact fields. Ensure mobile responsiveness.",
          dayNumber: 2,
          resourceLinks: JSON.stringify([
            { name: "Tailwind CSS Layout Guide", url: "https://tailwindcss.com/docs" },
            { name: "MDN CSS Layout Grid Reference", url: "https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout" },
          ]),
        },
        {
          title: "Interactive Checklist App with LocalStorage Sync",
          description: "Develop a functional interactive checkbox list using vanilla JavaScript or React. Allow items to be added, completed, and deleted. Save items to localStorage so they persist across page refreshes.",
          dayNumber: 3,
          resourceLinks: JSON.stringify([
            { name: "JavaScript DOM Operations", url: "https://javascript.info/document" },
            { name: "HTML5 LocalStorage Overview", url: "https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage" },
          ]),
        },
        {
          title: "Fetch and Render Live Data from JSON REST API",
          description: "Write an async/await fetch request to target a mock endpoint (JSONPlaceholder users/todos list). Loop through the parsed array and dynamically display data in styled cards showing user bios and stats.",
          dayNumber: 4,
          resourceLinks: JSON.stringify([
            { name: "JSONPlaceholder REST Endpoint", url: "https://jsonplaceholder.typicode.com/" },
            { name: "Using Fetch API Manual", url: "https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch" },
          ]),
        },
        {
          title: "Scaffold and Deploy Final Capstone Site live on Web",
          description: "Scaffold your final project with responsive navigation, styling, and interactivity. Host your code live on Vercel or GitHub Pages, and write a professional README.md with screenshots and live urls.",
          dayNumber: 5,
          resourceLinks: JSON.stringify([
            { name: "Vercel Fast Deploy", url: "https://vercel.com/docs" },
          ]),
        },
      ];
    } else if (isAndroid) {
      taskData = [
        {
          title: "Android Studio Installation & Emulator Verification",
          description: "Install Android Studio (latest stable version) and set up Android Virtual Device Emulator (AVD). Run a default template project. Submit a screenshot link showing the emulator running on your machine.",
          dayNumber: 1,
          resourceLinks: JSON.stringify([
            { name: "Android Studio Setup", url: "https://developer.android.com/studio" },
            { name: "Running AVD Emulator", url: "https://developer.android.com/studio/run/emulator" },
          ]),
        },
        {
          title: "Design a Material Design Login Screen Layout",
          description: "Create an XML ConstraintLayout or Jetpack Compose UI with email and password inputs. Write logic to check if inputs are valid (valid email syntax, password 6+ characters) and display error guidelines on incorrect input.",
          dayNumber: 2,
          resourceLinks: JSON.stringify([
            { name: "Material Design Specs", url: "https://material.io/design" },
            { name: "ConstraintLayout Reference", url: "https://developer.android.com/develop/ui/views/layout/constraint-layout" },
          ]),
        },
        {
          title: "Working Multi-Screen Activity Navigation Flow",
          description: "Develop a second dashboard screen. Set up Intent structures or Navigation Component links to safely route the enrollee from the Login page to the Dashboard, passing the verified email parameter.",
          dayNumber: 3,
          resourceLinks: JSON.stringify([
            { name: "Android Navigation Manual", url: "https://developer.android.com/guide/navigation" },
          ]),
        },
        {
          title: "Fetch Web REST API Data and Display in LazyColumn",
          description: "Use Retrofit or Ktor to request data from a public REST API. Parse the JSON array and bind it dynamically inside a scrollable Android RecyclerView or Compose LazyColumn layout with image loaders.",
          dayNumber: 4,
          resourceLinks: JSON.stringify([
            { name: "Retrofit Network Client", url: "https://square.github.io/retrofit/" },
            { name: "RecyclerView Bind Manual", url: "https://developer.android.com/develop/ui/views/layout/recyclerview" },
          ]),
        },
        {
          title: "Export Final Signed Release APK & Document Readme",
          description: "Generate a release key store, and compile a signed release APK file from Android Studio. Upload the APK file to Google Drive and write a setup guide explaining app features in your README.",
          dayNumber: 5,
          resourceLinks: JSON.stringify([
            { name: "Build Signed APK Guide", url: "https://developer.android.com/studio/publish/app-signing" },
          ]),
        },
      ];
    } else if (isAI) {
      taskData = [
        {
          title: "Anaconda Distribution & Python Environment Scaffolding",
          description: "Install Python 3.10+, Anaconda or Jupyter Notebooks. Build a script to verify clean imports of numpy, pandas, matplotlib, and scikit-learn. Print module versions as proof.",
          dayNumber: 1,
          resourceLinks: JSON.stringify([
            { name: "Anaconda Packages", url: "https://www.anaconda.com/" },
            { name: "Jupyter Setup Manual", url: "https://jupyter.org/install" },
          ]),
        },
        {
          title: "Data Exploratory Analysis and Matplotlib Graphs",
          description: "Load a CSV dataset (e.g. from Kaggle). Run Pandas data cleaning operations (fill null values, normalize columns, group indexes) and plot correlation heatmaps and scatter graphs.",
          dayNumber: 2,
          resourceLinks: JSON.stringify([
            { name: "Pandas Data Cleaning Manual", url: "https://pandas.pydata.org/docs" },
          ]),
        },
        {
          title: "Linear Regression Prediction Model Pipeline",
          description: "Scaffold a linear regression pipeline using Scikit-Learn to estimate values (e.g. housing or pricing indexes). Log your mean squared error evaluation score and plot the regression line.",
          dayNumber: 3,
          resourceLinks: JSON.stringify([
            { name: "Linear Regression Scikit", url: "https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LinearRegression.html" },
          ]),
        },
        {
          title: "Scaffold Image Classifier using PyTorch or Keras",
          description: "Design a Convolutional Neural Network (CNN) to categorize images from MNIST or CIFAR datasets. Train the model for 5 epochs and output performance curves detailing loss and accuracy.",
          dayNumber: 4,
          resourceLinks: JSON.stringify([
            { name: "TensorFlow Quick Guide", url: "https://www.tensorflow.org/tutorials" },
            { name: "PyTorch Basics Guide", url: "https://pytorch.org/tutorials" },
          ]),
        },
        {
          title: "Save Prediction Inference Engine & Write Markdown Guidelines",
          description: "Serialize your trained model parameters using pickle/h5 formats. Build a CLI script that takes input features and returns target label classifications, accompanied by setup guidelines.",
          dayNumber: 5,
          resourceLinks: JSON.stringify([
            { name: "Model Serialization Guide", url: "https://scikit-learn.org/stable/model_persistence.html" },
          ]),
        },
      ];
    } else {
      // DevOps / Cloud / UIUX fallback
      taskData = [
        {
          title: "Environment Setup, Version Control & Collaboration Config",
          description: "Install git, customize global settings, initialize local repository tracking, and document config parameters in a README.md file. Create first verification commit.",
          dayNumber: 1,
          resourceLinks: JSON.stringify([
            { name: "Git Documentation", url: "https://git-scm.com/doc" },
          ]),
        },
        {
          title: "Core Fundamentals & Docker Scaffolding",
          description: "Build the scaffold for your domain pipeline. Write configuration files (such as Dockerfiles, configuration scripts, or initial design components) and push them to Git.",
          dayNumber: 2,
          resourceLinks: JSON.stringify([
            { name: "Docker Configuration Guide", url: "https://docs.docker.com/" },
          ]),
        },
        {
          title: "Intermediate Integration & Validation Sprints",
          description: "Develop intermediate logic validations. Setup container builds, validation checks, style sheets, or wireframe flows to expand the workspace pipeline.",
          dayNumber: 3,
          resourceLinks: JSON.stringify([
            { name: "ProDevOpz Service Desk", url: "https://prodevopz.in/services" },
          ]),
        },
        {
          title: "API Connections, Databases & Hosting Integration",
          description: "Configure system connectors, cloud APIs, database schemas, or interactive frames. Verify that validations pass and database migrations complete cleanly.",
          dayNumber: 4,
          resourceLinks: JSON.stringify([
            { name: "Integrations Manual", url: "https://prodevopz.in/services" },
          ]),
        },
        {
          title: "Capstone Pipeline Deployment & Architecture Guidelines",
          description: "Build or export your final capstone work. Write a detailed configuration manual containing layout diagrams, features, and setup logs inside your GitHub repository.",
          dayNumber: 5,
          resourceLinks: JSON.stringify([
            { name: "ProDevOpz Guidelines", url: "https://prodevopz.in/internship" },
          ]),
        },
      ];
    }

    for (const task of taskData) {
      await prisma.task.create({
        data: {
          title: task.title,
          description: task.description,
          domain: domain,
          dayNumber: task.dayNumber,
          resourceLinks: task.resourceLinks,
        },
      });
    }
  }

  console.log("Seeded domain tasks.");

  // 3. Seed Client and Projects
  const client = await prisma.client.create({
    data: {
      name: "John Doe",
      email: "client@prodevopz.in",
      companyName: "Stellar AI Inc.",
      passwordHash: "client123", // Simple fallback hash
      projects: {
        create: [
          {
            title: "Stellar SaaS Platform",
            description: "Build an AI-powered automated video creation and scheduling SaaS platform for marketing agencies.",
            status: "DEVELOPMENT",
            progress: 65,
            repoUrl: "https://github.com/prodevopz/stellar-saas",
            meetingLink: "https://meet.google.com/abc-defg-hij",
            nextMilestone: "AI Video Editor Pipeline Integration",
            deadline: new Date(new Date().getTime() + 30 * 24 * 60 * 60 * 1000), // 30 days from now
          },
        ],
      },
      invoices: {
        create: [
          {
            invoiceNumber: "INV-2026-001",
            amount: 150000,
            dueDate: new Date(new Date().getTime() + 10 * 24 * 60 * 60 * 1000),
            status: "UNPAID",
          },
          {
            invoiceNumber: "INV-2026-002",
            amount: 250000,
            dueDate: new Date(new Date().getTime() - 5 * 24 * 60 * 60 * 1000),
            status: "PAID",
          },
        ],
      },
    },
  });

  console.log("Seeded clients and projects.");
  console.log("Seeding completed successfully!");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
