"use client";

import { useState } from "react";
import { MessageSquare, X, Send, Bot, Sparkles } from "lucide-react";

interface Message {
  sender: "user" | "bot";
  text: string;
}

export default function AIChatbot() {
  const [isOpen, setIsOpen] = useState(false);
  const [messages, setMessages] = useState<Message[]>([
    {
      sender: "bot",
      text: "Hello! I am the ProDevOpz AI Assistant. How can I help you build software or explore our internship programs today?",
    },
  ]);
  const [input, setInput] = useState("");

  const qaPairs = [
    {
      keywords: ["internship", "apply", "student", "registration"],
      answer: "Applying is simple! Head over to our Internship Portal (click 'Internship Portal' in the top header). Fill in your details, select your domain (e.g. React, Next.js, Node.js, AI, Mobile Dev), verify your email & phone, pay the one-time registration fee of ₹200, and your dashboard will immediately unlock with your Offer Letter!",
    },
    {
      keywords: ["msme", "certified", "legit", "recognition"],
      answer: "Yes, ProDevOpz is a fully registered MSME enterprise. All certificates generated by our system include the official MSME logo, a unique QR verification code, and are signed digitally. They are widely accepted by universities and corporate employers.",
    },
    {
      keywords: ["services", "custom", "software", "web", "android", "ios"],
      answer: "We offer end-to-end product development including: AI & LLM integration, Custom Web applications (React/Next.js/Node.js), Mobile App development (iOS/Android/Flutter/React Native), DevOps pipelines, Cloud infrastructure setup (AWS/Azure/Cloudflare), and Enterprise ERP/CRM implementations.",
    },
    {
      keywords: ["price", "cost", "estimator", "quote"],
      answer: "Our project pricing varies by scope. For startups and MVPs, we offer competitive rates. Use our interactive 'AI Project Estimator' on the Pricing page to select your modules and get a detailed timeline and cost estimate immediately!",
    },
    {
      keywords: ["certificate", "verify", "verification"],
      answer: "Anyone can verify ProDevOpz certificates! Go to the 'Verify Certificate' page from the footer menu. Enter the Certificate ID or scan the QR code printed on the certificate to see the student's name, photo, duration, domain, and completion status.",
    },
  ];

  const handleSend = () => {
    if (!input.trim()) return;

    const userText = input;
    const userMsg: Message = { sender: "user", text: userText };
    setMessages((prev) => [...prev, userMsg]);
    setInput("");

    // Simple keyword matching for automated responses
    setTimeout(() => {
      let botResponse =
        "Thank you for reaching out! A human representative or mentor will reply shortly, or you can check our Services and Internship sections for direct details. You can contact us at contactprodevopz@gmail.com.";

      const textLower = userText.toLowerCase();
      for (const pair of qaPairs) {
        if (pair.keywords.some((keyword) => textLower.includes(keyword))) {
          botResponse = pair.answer;
          break;
        }
      }

      setMessages((prev) => [...prev, { sender: "bot", text: botResponse }]);
    }, 600);
  };

  return (
    <div className="fixed bottom-6 right-6 z-50 flex flex-col items-end">
      {isOpen ? (
        <div className="w-[320px] sm:w-[360px] h-[450px] rounded-2xl glass-panel border-white/[0.08] shadow-2xl flex flex-col overflow-hidden animate-slide-up">
          {/* Header */}
          <div className="bg-gradient-to-r from-accent-orange/20 to-accent-purple/20 p-4 border-b border-white/[0.06] flex items-center justify-between">
            <div className="flex items-center gap-2">
              <div className="w-8 h-8 rounded-lg bg-accent-orange flex items-center justify-center">
                <Bot className="w-4 h-4 text-white" />
              </div>
              <div>
                <h4 className="text-xs font-bold text-white flex items-center gap-1">
                  ProDevOpz Assistant <Sparkles className="w-3 h-3 text-accent-orange" />
                </h4>
                <p className="text-[10px] text-foreground/50">Online • AI-First</p>
              </div>
            </div>
            <button
              onClick={() => setIsOpen(false)}
              className="p-1 rounded-lg text-foreground/50 hover:text-white hover:bg-white/5 transition-colors"
            >
              <X className="w-4 h-4" />
            </button>
          </div>

          {/* Messages list */}
          <div className="flex-grow p-4 overflow-y-auto flex flex-col gap-3 scrollbar-thin">
            {messages.map((msg, i) => (
              <div
                key={i}
                className={`flex ${
                  msg.sender === "user" ? "justify-end" : "justify-start"
                }`}
              >
                <div
                  className={`max-w-[80%] rounded-xl px-3 py-2 text-xs leading-relaxed ${
                    msg.sender === "user"
                      ? "bg-accent-orange text-white rounded-tr-none"
                      : "bg-white/[0.05] text-foreground/90 rounded-tl-none border border-white/[0.03]"
                  }`}
                >
                  {msg.text}
                </div>
              </div>
            ))}
          </div>

          {/* Input Panel */}
          <div className="p-3 border-t border-white/[0.06] bg-black/40 flex items-center gap-2">
            <input
              type="text"
              value={input}
              onChange={(e) => setInput(e.target.value)}
              onKeyDown={(e) => e.key === "Enter" && handleSend()}
              placeholder="Ask me about internships or services..."
              className="flex-grow bg-white/5 text-xs text-white rounded-xl px-3 py-2 border border-white/[0.06] focus:outline-none focus:border-accent-orange transition-colors"
            />
            <button
              onClick={handleSend}
              className="p-2 rounded-xl bg-accent-orange text-white hover:opacity-90 transition-opacity"
            >
              <Send className="w-3.5 h-3.5" />
            </button>
          </div>
        </div>
      ) : (
        <button
          onClick={() => setIsOpen(true)}
          className="w-12 h-12 sm:w-14 sm:h-14 rounded-full bg-gradient-to-tr from-accent-orange to-accent-purple text-white flex items-center justify-center shadow-2xl hover:scale-105 transition-transform"
        >
          <MessageSquare className="w-5.5 h-5.5 sm:w-6.5 sm:h-6.5" />
        </button>
      )}
    </div>
  );
}
